### PR TITLE
Plumbing: Babel 6 upgrade

### PR DESCRIPTION
**Pull request by fallenoak**
This brings Blizzardry in to the era of Babel 6 and configurable transforms / plugins.

Covers #96

### CODE REVIEW

**Comment by timkurvers** [comment]
Nice! 👍 

We might have to update the README too, to include the `.default` bits.

**Comment by timkurvers** [comment]
Should we test against Node 6?

**Comment by fallenoak** [comment]
I vote we do a PR to add Node 6 testing separate from this. There's a chance we'll need to do some fixes to work again in Node 6, and that would be out of the scope of the PR (I think).

**Comment by timkurvers** [comment]
Agree, let's do that later 👍

**Comment by fallenoak** [comment]
Just yanked the silly requirement that folks importing from Blizzardry would have to use ```.default``` on their imports. I think we're good to go now?

**Comment by timkurvers** [comment]
🎉

**Pull request merged**
