### PR TITLE
Feature: Portal parsing

### PR DESCRIPTION
**Pull request by fallenoak**
Adds parsing for MOPV, MOPT, and MOPR chunks.

### CODE REVIEW

**Comment by timkurvers** [comment]
Nice! I'm assuming the WMO we have in the specs doesn't have any portals to test against?

**Comment by fallenoak** [comment]
I'll check. We may want to move to a slightly more complicated WMO at some point, btw.

**Comment by fallenoak** [comment]
There are no portals present in ```trolltent_000.wmo```. I can confirm the parsing works fine, as I used it to implement portal culling in an experimental local branch.

Let's open an issue to pick a slightly more complicated WMO and WMO group to include for WMO specs.

**Comment by timkurvers** [comment]
Agree! 👍

**Comment by timkurvers** [comment]
🎉

**Pull request merged**
